### ISSUE TITLE
support for standard?

### ISSUE THREAD

**Issue by VikramTiwari** [houndci/hound#1192]
https://github.com/feross/standard

**Comment by teoljungberg** [comment]
Hi @VikramTiwari, we have support for Standard by using https://github.com/feross/eslint-config-standard.

In how to use it, you only need to add:

```json
{
  "extends": "standard"
}
```

To your `.eslintrc` as per their documentation.

**Comment by alexandrebini** [comment]
@teoljungberg What about standard extensions, like standard-react or standard-jsx?

I'm getting errors like this when I try to use it

```
Cannot find module 'eslint-config-standard-react'
Referenced from: .eslintrc
Error: Cannot find module 'eslint-config-standard-react'
    at ModuleResolver.resolve (/app/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/app/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/app/node_modules/eslint/lib/config/config-file.js:532:26)
    at configExtends.reduceRight.e (/app/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/app/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/app/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/app/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/app/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/app/node_modules/eslint/lib/config.js:260:26)
```

**Comment by teoljungberg** [comment]
@alexandrebini You can open up a PR adding `eslint-config-standard-react` to https://github.com/houndci/linters

**Comment by alexandrebini** [comment]
Hi @teoljungberg 

Here it is: https://github.com/houndci/linters/pull/144

Thanks
