### ISSUE TITLE
exception when running eslint

### ISSUE THREAD

**Issue by devilj** [houndci/hound#1544]
started seeing this exception in all our PRs opened after May 30:

```
.eslintrc:
	Configuration for rule "import/no-unresolved" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed 'false').

Error: .eslintrc:

at validateRuleOptions (/app/node_modules/eslint/lib/config/config-validator.js:119:19)

at Object.keys.forEach.id (/app/node_modules/eslint/lib/config/config-validator.js:162:9)

at Array.forEach ()

at validateRules (/app/node_modules/eslint/lib/config/config-validator.js:161:30)

at Object.validate (/app/node_modules/eslint/lib/config/config-validator.js:239:5)

at loadFromDisk (/app/node_modules/eslint/lib/config/config-file.js:507:19)

at Object.load (/app/node_modules/eslint/lib/config/config-file.js:550:20)

at Config.getLocalConfigHierarchy (/app/node_modules/eslint/lib/config.js:228:44)

at Config.getConfigHierarchy (/app/node_modules/eslint/lib/config.js:180:43)

at Config.getConfigVector (/app/node_modules/eslint/lib/config.js:287:21)
```

```
grep no-unresolved .eslintrc
        "import/no-unresolved": 0,
```

**Comment by gylaz** [comment]
Thank you for reporting this. We'll get a fix for this out asap.

**Comment by gylaz** [comment]
We've released a fix for this.

Please feel free to comment or re-open if the issue persists.
