### ISSUE TITLE
Update to eslint 5.6.0 (newest) to prevent spamming PRs when eslint configs for newer versions are used

### ISSUE THREAD

**Issue by douira** [houndci/hound#1580]
I get this eslint error:
```
.eslintrc:
	Configuration for rule "array-element-newline" is invalid:
	Value "consistent" should be equal to one of the allowed values.
	Value "consistent" should be object.
	Value "consistent" should match exactly one schema in oneOf.
Error: .eslintrc:

at validateRuleOptions (/home/linters/node_modules/eslint/lib/config/config-validator.js:119:19)

at Object.keys.forEach.id (/home/linters/node_modules/eslint/lib/config/config-validator.js:162:9)

at Array.forEach ()

at validateRules (/home/linters/node_modules/eslint/lib/config/config-validator.js:161:30)

at Object.validate (/home/linters/node_modules/eslint/lib/config/config-validator.js:239:5)

at loadFromDisk (/home/linters/node_modules/eslint/lib/config/config-file.js:507:19)

at Object.load (/home/linters/node_modules/eslint/lib/config/config-file.js:550:20)

at Config.getLocalConfigHierarchy (/home/linters/node_modules/eslint/lib/config.js:228:44)

at Config.getConfigHierarchy (/home/linters/node_modules/eslint/lib/config.js:180:43)

at Config.getConfigVector (/home/linters/node_modules/eslint/lib/config.js:287:21)
```
from hound on a PR with the message "Some files could not be reviewed due to errors:". The rule config in question in `.eslintrc` is:
```
 "array-element-newline": [
      "warn",
      "consistent"
    ],
```
It seems hound is using an older version of eslint that has a bug or just other expectations for the config of the array-element-newline rule. Running eslint 5.6.0 on this .eslintrc locally file produces no errors.

**Comment by douira** [comment]
Update: I've figured out that this is caused by hound using an older eslint version that has different default rules and different expectations for rule configs. It would be great if the eslint version could be raised to something recent so PRs aren't spammed with hound errors or wrongly reported linting errors.

**Comment by gylaz** [comment]
Yes, this is correct, Hound is running an older (v4.18.2) version of ESLint.

Unfortunately, updating it isn't straight forward, because otherwise we'll start spamming our users with new errors/violations that the newer version introduces (or no longer supports).

We're working on a strategy where users can opt-in to running the latest ESLint version. Otherwise, they'll be "frozen" to the older version.

**Comment by salbertson** [comment]
@douira linter version config is getting closer! https://github.com/houndci/hound/issues/1250#issuecomment-430701302

**Comment by salbertson** [comment]
@douira you can now configure linter versions for Hound! There is a list of supported linters with versions in our docs. http://help.houndci.com/configuration/supported-linters

To use a newer version of ESLint all you need to do is specify the version in your `.hound.yml`.

```
eslint:
  version: 5.7.0
```

Please let us know how it goes or if you have any questions.

**Comment by douira** [comment]
@salbertson Wow cool! I'll give it a try soon!
