### ISSUE TITLE
Stylelint - Few linters are throwing "Cound not find" errors

### ISSUE THREAD

**Issue by jerrythimothyj** [houndci/hound#1663]
```
Error: Could not find "stylelint-8-point-grid". Do you need a `configBasedir`?
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/getModulePath.js:18:11)
    at loadExtendedConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:186:22)
    at resultPromise.then.resultConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:161:16)
    at 
```

```
Error: Could not find "stylelint-declaration-use-variable". Do you need a `configBasedir`?
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/getModulePath.js:18:11)
    at config.plugins.concat.map.lookup (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:117:14)
    at Array.map ()
    at absolutizePaths (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:116:48)
    at Promise.resolve.then.then.then.augmentedConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:30:14)
    at 
```

```
Error: Undefined rule function-calc-no-invalid
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:302:13)
    at Array.forEach ()
    at normalizeAllRuleSettings (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at
```

```
Error: Undefined rule selector-max-pseudo-class
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:302:13)
    at Array.forEach ()
    at normalizeAllRuleSettings (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at 
```

```
Error: Undefined rule linebreaks
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:302:13)
    at Array.forEach ()
    at normalizeAllRuleSettings (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at 
```

```
Error: Undefined rule no-empty-first-line
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:302:13)
    at Array.forEach ()
    at normalizeAllRuleSettings (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:89:14)
    at 
```

Below is my stylelintrc file:

```
{
  "defaultSeverity": "error",
  "plugins": [
    "stylelint-declaration-use-variable",
    "stylelint-a11y",
    "stylelint-declaration-block-no-ignored-properties",
    "stylelint-group-selectors",
    "stylelint-no-indistinguishable-colors",
    "stylelint-order",
    "stylelint-selector-no-empty",
    "stylelint-value-no-unknown-custom-properties"
  ],
  "extends": ["stylelint-8-point-grid"],
  "rules": {
    "color-no-invalid-hex": true,
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": true,
    "function-calc-no-invalid": true,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "string-no-newline": true,
    "unit-no-unknown": true,
    "property-no-unknown": true,
    "keyframe-declaration-no-important": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "block-no-empty": true,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": true,
    "media-feature-name-no-unknown": true,
    "at-rule-no-unknown": true,
    "comment-no-empty": true,
    "no-descending-specificity": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-extra-semicolons": true,
    "no-invalid-double-slash-comments": true,
    "color-named": "never",
    "number-max-precision": 2,
    "shorthand-property-no-redundant-values": true,
    "value-no-vendor-prefix": true,
    "property-no-vendor-prefix": true,
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-no-important": false,
    "declaration-block-single-line-max-declarations": 1,
    "selector-max-attribute": 3,
    "selector-max-class": 3,
    "selector-max-combinators": 3,
    "selector-max-compound-selectors": 3,
    "selector-max-empty-lines": 0,
    "selector-max-id": 1,
    "selector-max-pseudo-class": 2,
    "selector-max-type": 3,
    "selector-max-universal": 2,
    "selector-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": true,
    "at-rule-no-vendor-prefix": true,
    "max-nesting-depth": 2,
    "no-unknown-animations": true,
    "color-hex-case": "lower",
    "color-hex-length": "long",
    "font-family-name-quotes": "always-where-recommended",
    "font-weight-notation": "numeric",
    "function-comma-space-after": "always",
    "function-max-empty-lines": 0,
    "function-url-quotes": "always",
    "number-leading-zero": "always",
    "number-no-trailing-zeros": true,
    "string-quotes": "double",
    "length-zero-no-unit": true,
    "unit-case": "lower",
    "value-keyword-case": "lower",
    "value-list-comma-space-after": "always",
    "value-list-max-empty-lines": 0,
    "property-case": "lower",
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-block-semicolon-newline-after": "always-multi-line",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never",
    "declaration-block-trailing-semicolon": "always",
    "block-closing-brace-empty-line-before": "never",
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always-multi-line",
    "block-closing-brace-space-after": "always-single-line",
    "block-closing-brace-space-before": "always-single-line",
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-newline-before": "never-single-line",
    "block-opening-brace-space-after": "always-single-line",
    "block-opening-brace-space-before": "always",
    "selector-attribute-brackets-space-inside": "never",
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    "selector-attribute-quotes": "always",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-descendant-combinator-no-non-space": true,
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-parentheses-space-inside": "never",
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-colon-notation": "double",
    "selector-type-case": "lower",
    "selector-list-comma-newline-after": "always-multi-line",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always-single-line",
    "selector-list-comma-space-before": "never",
    "rule-empty-line-before": [
      "always-multi-line",
      {
        "except": ["after-single-line-comment", "first-nested"],
        "ignore": ["after-comment", "first-nested"]
      }
    ],
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": "lower",
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always-single-line",
    "media-query-list-comma-space-before": "never",
    "at-rule-empty-line-before": [
      "always",
      {
        "except": ["after-same-name", "blockless-after-same-name-blockless", "blockless-after-blockless", "first-nested"],
        "ignore": ["after-comment", "first-nested", "blockless-after-same-name-blockless", "blockless-after-blockless"]
      }
    ],
    "at-rule-name-case": "lower",
    "at-rule-name-newline-after": "always-multi-line",
    "at-rule-name-space-after": "always-single-line",
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": "never",
    "comment-empty-line-before": [
      "always",
      {
        "except": ["first-nested"],
        "ignore": ["after-comment", "stylelint-commands"]
      }
    ],
    "comment-whitespace-inside": "always",
    "indentation": 2,
    "linebreaks": "unix",
    "max-empty-lines": 1,
    "no-eol-whitespace": true,
    "no-missing-end-of-source-newline": true,
    "no-empty-first-line": true,

    "sh-waqar/declaration-use-variable": [["/color/", "font-size"]],

    "plugin/8-point-grid": {
      "base": 4,
      "whitelist": ["2px", "1px"],
      "ignore": ["width", "height"]
    },

    "a11y/media-prefers-reduced-motion": true,
    "a11y/no-outline-none": true,
    "a11y/selector-pseudo-class-focus": true,
    "a11y/content-property-no-static-value": [true, { "severity": "warning" }],
    "a11y/font-size-is-readable": [true, { "severity": "warning" }],
    "a11y/line-height-is-vertical-rhythmed": [true, { "severity": "warning" }],
    "a11y/no-display-none": [true, { "severity": "warning" }],
    "a11y/no-spread-text": [true, { "severity": "warning" }],
    "a11y/no-obsolete-attribute": [true, { "severity": "warning" }],
    "a11y/no-obsolete-element": [true, { "severity": "warning" }],
    "a11y/no-text-align-justify": [true, { "severity": "warning" }],
    "a11y/media-prefers-color-scheme": [true, { "severity": "warning" }],

    "plugin/declaration-block-no-ignored-properties": true,

    "plugin/stylelint-group-selectors": true,

    "plugin/stylelint-no-indistinguishable-colors": [true, { "threshold": 0 }],

    "order/properties-alphabetical-order": true,

    "plugin/stylelint-selector-no-empty": true,

    "csstools/value-no-unknown-custom-properties": true
  }
}
```

**stylelint version: 9.10.1**

**Comment by gnclmorais** [comment]
I’m getting a similar warning. I’ve noticed Stylint’s supported version is [listed at

**Comment by gnclmorais** [comment]
I’m getting a similar warning. I’ve noticed Stylint’s supported version is [listed as 9.1.3](http://help.houndci.com/configuration/supported-linters), which is from… [March of last year](https://github.com/stylelint/stylelint/releases/tag/9.1.3). Can we get an update on this, please?

**Comment by jerrythimothyj** [comment]
Why is it closed? @gylaz

**Comment by gnclmorais** [comment]
I have exactly the same question, @gylaz… 🤔

**Comment by gylaz** [comment]
GitHub auto-closed this because a PR referencing this issue was merged in. We'll get it released today.

**Comment by gnclmorais** [comment]
@gylaz, could you link that PR here, please? I thought mentions would be automatically done by GitHub… 🤔

**Comment by gylaz** [comment]
The repository that runs our linters is private. Apparently, that still has the effect of closing the related issues, but doesn't actually display the link publicly (I can see the linked PR here since I'm part of the private repo).

We've released these changes (linter upgrade included). Please let us know if you see any more of these issues.

**Comment by gnclmorais** [comment]
Great, thank you for clarifying! Don’t forget to update http://help.houndci.com/configuration/supported-linters 😉
