### ISSUE TITLE
Support for eslint-config-google

### ISSUE THREAD

**Issue by betanummeric** [houndci/hound#1717]
Hello! Since I've added [eslint-config-google](https://github.com/google/eslint-config-google) to my `package.json`, `yarn.lock` and `.eslintrc.json`, I get the following error:

```
Cannot find module 'eslint-config-google'
Referenced from: .eslintrc
Error: Cannot find module 'eslint-config-google'
    at ModuleResolver.resolve (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config/config-file.js:479:28)
    at load (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config/config-file.js:551:26)
    at configExtends.reduceRight (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config/config-file.js:425:36)
    at Array.reduceRight ()
    at applyExtends (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config/config-file.js:403:26)
    at loadFromDisk (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config/config-file.js:523:22)
    at Object.load (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config/config-file.js:559:20)
    at Config.getLocalConfigHierarchy (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/home/linters/app/versions/eslint-4.18.2/node_modules/eslint/lib/config.js:179:43)
```

Is _eslint-config-google_ supported by hound? If not, can you add support for it?

**Comment by gylaz** [comment]
This plugin is now supported in ESLint versions `5.16.0`+.
