### ISSUE TITLE
Organisation specific shared rule set.

### ISSUE THREAD

**Issue by billybonks** [houndci/hound#1735]
We have a shared lint rule set for all our applications, but from what i understand in order to get it to work with hound we need to request it here first ?

```
Some files could not be reviewed due to errors:
Error: Cannot find module '@tradegecko/eslint-config-ember'

Error: Cannot find module '@tradegecko/eslint-config-ember'
Referenced from: .eslintrc
    at ModuleResolver.resolve (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config/config-file.js:507:28)
    at load (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config/config-file.js:579:26)
    at configExtends.reduceRight (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight ()
    at applyExtends (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config/config-file.js:431:26)
    at loadFromDisk (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config/config-file.js:551:22)
    at Object.load (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/home/linters/app/versions/eslint-5.16.0/node_modules/eslint/lib/config.js:192:43)
```

**Comment by billybonks** [comment]
the package is public https://www.npmjs.com/package/@tradegecko/eslint-config-ember

**Comment by gylaz** [comment]
Did the org-wide config solution not work for you? You can add `.hound.yml` to the shared config repo, and specify your eslint `config_file`. This has the added benefit of not needing us to update your package when it changes.

**Comment by billybonks** [comment]
@gylaz could you point me to some documentation please ?

**Comment by gylaz** [comment]
Here you go: http://help.houndci.com/en/articles/3279357-shared-organiation-wide-configuration
