### ISSUE TITLE
Rubocop extensions support?

### ISSUE THREAD

**Issue by bignimbus** [houndci/hound#1756]
Hello Hound team,

Thanks for your awesome work on this tool.  When I added the `rubocop-i18n` tool to our Gemfile and included it in our rubocop configuration, I get the following message from Hound in my pull request:

```
Some files could not be reviewed due to errors:

cannot load such file -- rubocop-i18n
cannot load such file -- rubocop-i18n
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/config_loader_resolver.rb:15:in `require'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/config_loader_resolver.rb:11:in `each'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/config_loader.rb:44:in `load_file'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/config_loader.rb:82:in `configuration_from_file'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/config_store.rb:44:in `for'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/cli.rb:206:in `apply_default_formatter'
/home/linters/.bundle/gems/rubocop-0.64.0/lib/rubocop/cli.rb:46:in `run'
/home/linters/.bundle/gems/rubocop-0.64.0/exe/rubocop:13:in `block in '
/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/linters/.bundle/gems/rubocop-0.64.0/exe/rubocop:12:in `'
/home/linters/.bundle/bin/rubocop:23:in `load'
/home/linters/.bundle/bin/rubocop:23:in `'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in '
/usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `'
```

Does Hound support extensions for Rubocop?  Thank you!

**Comment by gylaz** [comment]
We do support rubocop extensions, but we have to manually whitelist them. I'll update this when we add this one to our systems.

**Comment by bignimbus** [comment]
Thank you for the update, @gylaz!

**Comment by mcmire** [comment]
Can you add rubocop-rails to the whitelist as well? This is a pretty popular extension (as it was extracted a while back) but it seems that Hound doesn't know how to handle it right now.

**Comment by gylaz** [comment]
@mcmire Which version of RuboCop are you using with Hound? We support `rubocop-rails` from RuboCop v0.71.0+.

**Comment by gylaz** [comment]
@bignimbus We've now added support for `rubocop-i18n` extension.

**Comment by mcmire** [comment]
@gylaz Ah, this particular project is still using Rubocop 0.64.0 so that would make sense why I'm seeing an error from Hound. Thanks!

**Comment by iseth** [comment]
Would it be possible to add the standardrb rubocop syntax:
```yml
require: standard

inherit_gem:
  standard: config/base.yml
```
