### ISSUE TITLE
Support for stylelint-config-sass-guidelines and update stylelint

### ISSUE THREAD

**Issue by emattias** [houndci/hound#1771]
With a `.stylelintrc.json` file with:

```
{
  "extends": [
    "stylelint-config-sass-guidelines",
    "stylelint-config-prettier"
  ],
  ...
}
```

I get this error:

```
Error: Could not find "stylelint-config-sass-guidelines". Do you need a `configBasedir`?
    at module.exports (/home/linters/app/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at getModulePath (/home/linters/app/node_modules/stylelint/lib/utils/getModulePath.js:26:11)
    at loadExtendedConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:194:22)
    at resultPromise.then.resultConfig (/home/linters/app/node_modules/stylelint/lib/augmentConfig.js:168:16)
```

I have added [stylelint-config-sass-guidelines](https://github.com/bjankord/stylelint-config-sass-guidelines) to my package.json but you are not using my package.json packages but have your own whitelist of npm packages, if I have understood correctly? Is there a list of which those are (and which versions?)

Also the [supported stylelint version](http://help.houndci.com/en/articles/2461415-supported-linters) `10.1.0` is pretty old. The latest at the moment is [13.0.0](https://github.com/stylelint/stylelint/releases). Could it be updated?

**Comment by magnito777** [comment]
OK am following

**Comment by benjheath0** [comment]
Did you ever figure this out?

**Comment by adrianmiles** [comment]
> Did you ever figure this out?

I had this issue after cloning a project with style lint in it and not running yarn / npm install  (since I had cloned it there were no node_modules yet). I jumped straight into trying to debug without bothering to install everything 😓  After doing so everything behaved
