### ISSUE TITLE
ESlint 8.1.0 does not work

### ISSUE THREAD

**Issue by kgunbin** [houndci/hound#1862]
Hello
With the `.hound.yml` containing
```yaml
eslint:
  enabled: true
  config_file: .eslintrc.hound.yml
  ignore_file: .eslintignore
  version: 8.1.0
```

and `package.json` containing 
```json
  "engines": {
    "npm" : ">=6.0.0",
    "node" : ">=14.0.0"
  }
```
We get the errors like
```
Oops! Something went wrong! :(
ESLint: 8.1.0
TypeError: Module.createRequire is not a function
    at Object. (/home/linters/app/versions/eslint-8.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2359:26)
    at Module._compile (/home/linters/app/versions/eslint-8.1.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/linters/app/versions/eslint-8.1.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object. (/home/linters/app/versions/eslint-8.1.0/node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
```

This indicates the outdated (before 12.2) Nodejs version used to run ESlint.

**Comment by mihilbabin** [comment]
I'm having the same problem after app was migrated to Node 14+

**Comment by munezerobagira** [comment]
How did you manage to tackle that?
