### ISSUE TITLE
Whitelist rubocop-thread_safety extension

### ISSUE THREAD

**Issue by docwhat** [houndci/hound#1874]
Please add `rubocop-thread_safety` to the extension whitelist for hound-ci.  Thank you! 🙇 

> Some files could not be reviewed due to errors:
> 
> ```
> cannot load such file -- rubocop-thread_safety
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_loader_resolver.rb:16:in `require'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_loader_resolver.rb:16:in `block in resolve_requires'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_loader_resolver.rb:12:in `each'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_loader.rb:43:in `load_file'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_loader.rb:103:in `configuration_from_file'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_store.rb:58:in `for_dir'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/config_store.rb:37:in `for_pwd'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/cli.rb:124:in `apply_default_formatter'
> /home/linters/.bundle/gems/rubocop-0.91.0/lib/rubocop/cli.rb:40:in `run'
> /home/linters/.bundle/gems/rubocop-0.91.0/exe/rubocop:13:in `block in '
> /usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
> /home/linters/.bundle/gems/rubocop-0.91.0/exe/rubocop:12:in `'
> /home/linters/.bundle/bin/rubocop:23:in `load'
> /home/linters/.bundle/bin/rubocop:23:in `'
> /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
> /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
> /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
> /usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
> /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
> /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
> /usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
> /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
> /usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
> /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in '
> /usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
> /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `'
> /usr/local/bin/bundle:23:in `load'
> /usr/local/bin/bundle:23:in `'
> ```

**Comment by docwhat** [comment]
Is there any progress on this? Is there someone I should contact about this?

A related issue is [knowing what extensions are supported](https://github.com/houndci/hound/issues/1770https://github.com/houndci/hound/issues/1770).
